services:
  - type: web
    name: radiology-backend
    env: node
    buildCommand: "npm install && pip install -r requirements.txt"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
